# Generated by Django 2.0.1 on 2018-06-17 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('section', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Catering/Hospitality', 'Catering/Hospitality'), ('Education', 'Education'), ('Event Management', 'Event Management'), ('IT/Programming', 'IT/Programming'), ('Fashion', 'Fashion'), ('Health', 'Health'), ('IT/Programming', 'IT/Programming'), ('Technology', 'Technology'), ('General', 'General')], max_length=40)),
                ('enterprise', models.CharField(blank=True, max_length=100, null=True)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('article', models.TextField()),
                ('image_1', models.ImageField(blank=True, default='image', null=True, upload_to='image')),
                ('image_2', models.ImageField(blank=True, default='image', null=True, upload_to='image')),
                ('image_3', models.ImageField(blank=True, default='image', null=True, upload_to='image')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('article_author', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(blank=True, default='comment', null=True, upload_to='comment')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Marketplace.article')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessname', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, default='logo', null=True, upload_to='logo')),
                ('business_profile', models.CharField(max_length=500)),
                ('intern_ad', models.TextField(default='Add internship description here')),
                ('added_by', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Marketplace.article')),
            ],
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('section', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Catering/Hospitality', 'Catering/Hospitality'), ('Education', 'Education'), ('Event Management', 'Event Management'), ('IT/Programming', 'IT/Programming'), ('Fashion', 'Fashion'), ('Health', 'Health'), ('IT/Programming', 'IT/Programming'), ('Technology', 'Technology'), ('General', 'General')], default='Agriculture', max_length=40)),
                ('businessname', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, default='logo', null=True, upload_to='logo')),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, default='http://example.com', null=True)),
                ('services', models.TextField(default='Add a brief description of your products/services here')),
                ('added_by', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='liked',
            unique_together={('added_by', 'post')},
        ),
    ]
