# Generated by Django 2.0.1 on 2018-07-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_auto_20180717_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='quote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
