# Generated by Django 2.0.1 on 2018-08-09 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0005_auto_20180809_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
