# Generated by Django 2.0.1 on 2018-08-11 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0006_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
