# Generated by Django 2.0.1 on 2018-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0008_internship_intern_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=150)),
                ('workshop_flyer', models.ImageField(blank=True, default='workshop', null=True, upload_to='workshop')),
                ('workshop_details', models.TextField(default='Add workshop/training details here')),
                ('added_by', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
